DROP DATABASE IF EXISTS comicsdb;
CREATE DATABASE comicsdb;

\c comicsdb;

CREATE TABLE COMICS (
  ID SERIAL PRIMARY KEY,
  TITLE TEXT NOT NULL
);

CREATE TABLE VOLUMES (
  ID SERIAL PRIMARY KEY,
  NUMBER SMALLINT NOT NULL,
  TITLE TEXT,
  COMIC_ID INTEGER REFERENCES COMICS (ID) NOT NULL 
);

CREATE TABLE CHAPTERS (
  ID SERIAL PRIMARY KEY,
  NUMBER SMALLINT NOT NULL,
  TITLE TEXT,
  VOLUME_ID INTEGER REFERENCES VOLUMES (ID) NOT NULL 
);

CREATE TABLE PAGES (
  ID SERIAL PRIMARY KEY,
  CHAPTER_ID INTEGER REFERENCES CHAPTERS (ID) NOT NULL,
  URL VARCHAR(500),
  ORDER_NUMBER DECIMAL
);
