\c comicsdb;

DELETE FROM COMICS;
DELETE FROM VOLUMES;
DELETE FROM CHAPTERS;
DELETE FROM PAGES;

INSERT INTO COMICS (TITLE) VALUES ('Default comic');
INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (1, 'First volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));

INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (2, 'Second volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));
INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (3, 'Third volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));
INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (3, 'Third volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));

INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (1, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'First volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (2, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'First volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (3, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'First volume'));

INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (1, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (2, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (3, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (3, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));