\c comicsdb;

DELETE FROM COMICS;
DELETE FROM VOLUMES;
DELETE FROM CHAPTERS;
DELETE FROM PAGES;

INSERT INTO COMICS (TITLE) VALUES ('Default comic');
INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (1, 'First volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));

INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (2, 'Second volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));
INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (3, 'Third volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));
INSERT INTO VOLUMES (NUMBER, TITLE, COMIC_ID) VALUES (3, 'Third volume', (SELECT ID FROM COMICS WHERE TITLE = 'Default comic'));

INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (1, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'First volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (2, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'First volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (3, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'First volume'));

INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (1, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (2, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (3, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));
INSERT INTO CHAPTERS (NUMBER, TITLE, VOLUME_ID) VALUES (3, NULL, (SELECT ID FROM VOLUMES WHERE TITLE = 'Second volume'));

INSERT INTO PAGES (CHAPTER_ID, THUMBNAIL_URL, FULLSIZE_URL, ORDER_NUMBER) VALUES ((SELECT CHAPTER_ID FROM V_VOLUMES_CHAPTERS WHERE VOLUME_NUMBER = 1 AND CHAPTER_NUMBER = 1), 'images/volume1/chapter1/thumbnails/page1.png', 'images/volume1/chapter1/fullsize/page1.png', 1);
INSERT INTO PAGES (CHAPTER_ID, THUMBNAIL_URL, FULLSIZE_URL, ORDER_NUMBER) VALUES ((SELECT CHAPTER_ID FROM V_VOLUMES_CHAPTERS WHERE VOLUME_NUMBER = 1 AND CHAPTER_NUMBER = 1), 'images/volume1/chapter1/thumbnails/page2.png', 'images/volume1/chapter1/fullsize/page2.png', 2);
INSERT INTO PAGES (CHAPTER_ID, THUMBNAIL_URL, FULLSIZE_URL, ORDER_NUMBER) VALUES ((SELECT CHAPTER_ID FROM V_VOLUMES_CHAPTERS WHERE VOLUME_NUMBER = 1 AND CHAPTER_NUMBER = 1), 'images/volume1/chapter1/thumbnails/page3.png', 'images/volume1/chapter1/fullsize/page3.png', 3);
INSERT INTO PAGES (CHAPTER_ID, THUMBNAIL_URL, FULLSIZE_URL, ORDER_NUMBER) VALUES ((SELECT CHAPTER_ID FROM V_VOLUMES_CHAPTERS WHERE VOLUME_NUMBER = 1 AND CHAPTER_NUMBER = 1), 'images/volume1/chapter1/thumbnails/page4.png', 'images/volume1/chapter1/fullsize/page4.png', 4);